03-lection1
js-tasks-ru/htmlcss-20240412_ivan-glushkov1997 pull request #3
Opened 2024-04-19 15:05 UTC by good-gis

2024-04-19 15:07 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-21 09:27 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-04-22 14:29 UTC, GSemikozov requested changes

2024-04-22 14:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +@import "assets/css/main.css";
ни в коем случае) наоборот, файлы стилей компонентов подключаем в main.css чтобы они были доступны на уровне всего проекта

2024-04-22 14:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 100%;
лишнее (height: 48px - подходит)

2024-04-22 14:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    height: 100%;
и еще не хватает паддингов

2024-04-22 14:29 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_size_l {
лишнее (у нас всего 1 размер)

2024-04-22 17:28 UTC, good-gis commented on 03-lection1/01-button/button.css
> +@import "assets/css/main.css";
Все понял, увидел, что в HTML уже подключены стили

2024-04-26 06:54 UTC, GSemikozov requested changes

2024-04-26 06:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
лишнее ограничение ширины)

2024-04-26 06:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding-top: 15px;
слева-справа тоже надо

2024-04-29 10:54 UTC, GSemikozov requested changes

2024-04-29 10:54 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
все еще актуально (надо удалить width)

2024-05-02 08:05 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-05-02 08:10 UTC, jsru-1 commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-05-05 13:32 UTC, GSemikozov approved these changes

2024-05-05 13:33 UTC, merged