feat: histogram
js-tasks-ru/htmlcss-20240412_ivan-glushkov1997 pull request #5
Opened 2024-04-25 16:31 UTC by good-gis

2024-04-25 16:31 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-04-26 06:58 UTC, GSemikozov requested changes

2024-04-26 06:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram_title {
.histogram__title

2024-04-26 06:58 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-right: 1px;
проще через gap у родителя

2024-04-27 13:28 UTC, good-gis commented on 04-lection2/01-histogram/histogram.css
> +.histogram_title {
поправил, спасибо

2024-04-27 13:31 UTC, good-gis commented on 04-lection2/01-histogram/histogram.css
> +    margin-right: 1px;
точно и лишние стили выпилил, класс
спасибо, поправил

2024-04-29 10:55 UTC, GSemikozov approved these changes

2024-04-29 10:55 UTC, merged